 name 			= "Squad FSM Modules";              // Name of your mod
 author 		= "Yipman (Design), Tally (Code)";  // Affects Arma 3 Launcher, when the mod are loaded as local
 logo 			= "Small_Icon.paa";                 // Logo displayed in the main menu
 logoOver 		= "Small_Icon.paa";                 // When the mouse is over, in the main menu
 tooltip 		= "Squad FSM Modules";
 tooltipOwned 	= "credit_mod";                     // Tool tip displayed when the mouse is left over, in the main menu
 picture 		= "Small_Icon.paa";                 // Picture displayed from the expansions menu. Optimal size is 2048x1024
 actionName 	= "Discord";                        // Button-text
 action 		= "https://discord.gg/bRTqWJzeza";  // Website URL, that can be accessed from the expansions menu
 overview 		= "Modules for squad FSM";          // Supports structured text
 hideName 		= 0;                                // Hide the extension name
 hidePicture	= 0;	                            // Hide the extension menu
 dlcColor[] 	= {0.23,0.39,0.30, 0.5};            // Color used for DLC stripes and backgrounds (RGBA)
 logoSmall 		= "Small_Icon.paa";                 // Display in creative lists, next to the entities added by the mod